
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class Adding extends javax.swing.JFrame {

   String surl = "jdbc:mysql://localhost:3306/data";
    String suser = "root";
    String spassword = "@root123@";
    public Adding() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        nb = new javax.swing.JLabel();
        Model = new javax.swing.JTextField();
        x = new javax.swing.JLabel();
        zx = new javax.swing.JLabel();
        z = new javax.swing.JLabel();
        Years = new javax.swing.JTextField();
        Mileage = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        xz = new javax.swing.JLabel();
        Color = new javax.swing.JTextField();
        vhnb = new javax.swing.JLabel();
        Conditions = new javax.swing.JTextField();
        gvhjbmn = new javax.swing.JLabel();
        Powers = new javax.swing.JTextField();
        dsfs = new javax.swing.JLabel();
        SUV = new javax.swing.JTextField();
        ADD = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 255, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD Details");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 80));

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nb.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        nb.setForeground(new java.awt.Color(0, 153, 153));
        nb.setText("Model");
        kGradientPanel2.add(nb, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 24, 150, 36));

        Model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelActionPerformed(evt);
            }
        });
        kGradientPanel2.add(Model, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 28, 149, 36));

        x.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        x.setForeground(new java.awt.Color(0, 153, 153));
        x.setText("Year");
        kGradientPanel2.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 100, 94, 42));

        zx.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        zx.setForeground(new java.awt.Color(0, 153, 153));
        zx.setText("Mileage");
        kGradientPanel2.add(zx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 94, 27));

        z.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        z.setForeground(new java.awt.Color(0, 153, 153));
        z.setText("Price");
        kGradientPanel2.add(z, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 102, 30));
        kGradientPanel2.add(Years, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 104, 149, 42));
        kGradientPanel2.add(Mileage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 160, 39));
        kGradientPanel2.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 260, 149, 40));

        xz.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        xz.setForeground(new java.awt.Color(0, 153, 153));
        xz.setText("Color");
        kGradientPanel2.add(xz, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 34, 98, 36));

        Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorActionPerformed(evt);
            }
        });
        kGradientPanel2.add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 38, 166, 36));

        vhnb.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        vhnb.setForeground(new java.awt.Color(0, 153, 153));
        vhnb.setText("Condition");
        kGradientPanel2.add(vhnb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 42));
        kGradientPanel2.add(Conditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 104, 166, 42));

        gvhjbmn.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        gvhjbmn.setForeground(new java.awt.Color(0, 153, 153));
        gvhjbmn.setText("Power");
        kGradientPanel2.add(gvhjbmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 174, 98, 39));

        Powers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowersActionPerformed(evt);
            }
        });
        kGradientPanel2.add(Powers, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 178, 166, 39));

        dsfs.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        dsfs.setForeground(new java.awt.Color(0, 153, 153));
        dsfs.setText("SUV");
        kGradientPanel2.add(dsfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 98, 40));
        kGradientPanel2.add(SUV, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 166, 40));

        ADD.setBorder(null);
        ADD.setText("ADD");
        ADD.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ADD.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        ADD.setkEndColor(new java.awt.Color(0, 153, 153));
        ADD.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        ADD.setkHoverForeGround(new java.awt.Color(0, 153, 153));
        ADD.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        ADD.setkStartColor(new java.awt.Color(0, 255, 204));
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        kGradientPanel2.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 336, 164, -1));

        kButton2.setBorder(null);
        kButton2.setText("BACK");
        kButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        kButton2.setkEndColor(new java.awt.Color(0, 153, 153));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(0, 153, 153));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton2.setkStartColor(new java.awt.Color(0, 255, 204));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 336, 174, -1));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 780, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorActionPerformed

    private void PowersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowersActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
                 try {
            Connection con = DriverManager.getConnection(surl,suser,spassword);
            Statement statement = con.createStatement();
         
          PreparedStatement pst= con.prepareStatement("insert into Adding values(?,?,?,?,?,?,?,?)");
          JOptionPane.showMessageDialog(null, "Record Inserted...");  
          
          
           pst.setString(1,Model.getText());     
            pst.setString(2,Years.getText());  
             pst.setString(3,Mileage.getText());   
               pst.setString(4,Price.getText()); 
              
               pst.setString(5,Color.getText()); 
            pst.setString(6,Conditions.getText()); 
              pst.setString(7,Powers.getText()); 
         pst.setString(8,SUV.getText());
         
          int res=pst.executeUpdate();
         
        }
        catch(Exception e)
        {
            System.err.println(e.toString());
        }
    
    }//GEN-LAST:event_ADDActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
          NewJFrame wu=new   NewJFrame();
                     wu.show();
                     dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void ModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton ADD;
    private javax.swing.JTextField Color;
    private javax.swing.JTextField Conditions;
    private javax.swing.JTextField Mileage;
    private javax.swing.JTextField Model;
    private javax.swing.JTextField Powers;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField SUV;
    private javax.swing.JTextField Years;
    private javax.swing.JLabel dsfs;
    private javax.swing.JLabel gvhjbmn;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel nb;
    private javax.swing.JLabel vhnb;
    private javax.swing.JLabel x;
    private javax.swing.JLabel xz;
    private javax.swing.JLabel z;
    private javax.swing.JLabel zx;
    // End of variables declaration//GEN-END:variables
}
