/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class forgot2 extends javax.swing.JFrame {

    String surl = "jdbc:mysql://localhost:3306/data";
    String suser = "root";
    String spassword = "@root123@";
    public forgot2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbluser = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnewpassword = new javax.swing.JPasswordField();
        btnconfirm = new javax.swing.JButton();
        lblheader = new javax.swing.JLabel();
        btnsignin = new javax.swing.JButton();
        btnok = new javax.swing.JButton();
        txtsquestion = new javax.swing.JTextField();
        lblpass1 = new javax.swing.JLabel();
        txtanswer = new javax.swing.JPasswordField();
        lblpass2 = new javax.swing.JLabel();
        lblpass3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(550, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbluser.setFont(new java.awt.Font("Futura Md BT", 0, 20)); // NOI18N
        lbluser.setForeground(new java.awt.Color(255, 255, 255));
        lbluser.setText("Email/Mobile");
        jPanel1.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 30));

        txtid.setFont(new java.awt.Font("Futura Md BT", 0, 20)); // NOI18N
        txtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtid.setText("Username");
        txtid.setMinimumSize(new java.awt.Dimension(100, 40));
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidFocusLost(evt);
            }
        });
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 330, -1));

        txtnewpassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtnewpassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtnewpassword.setMinimumSize(new java.awt.Dimension(100, 40));
        txtnewpassword.setPreferredSize(new java.awt.Dimension(109, 31));
        txtnewpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnewpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnewpasswordFocusLost(evt);
            }
        });
        jPanel1.add(txtnewpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 420, -1));

        btnconfirm.setBackground(new java.awt.Color(0, 153, 153));
        btnconfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirm.setText("Confirm");
        btnconfirm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnconfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnconfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnconfirmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnconfirmMousePressed(evt);
            }
        });
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 100, 40));

        lblheader.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblheader.setForeground(new java.awt.Color(255, 255, 255));
        lblheader.setText("Forgot Password");
        jPanel1.add(lblheader, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 290, 70));

        btnsignin.setBackground(new java.awt.Color(0, 153, 153));
        btnsignin.setForeground(new java.awt.Color(255, 255, 255));
        btnsignin.setText("SignIn");
        btnsignin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnsigninMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsigninMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsigninMouseEntered(evt);
            }
        });
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });
        jPanel1.add(btnsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 100, 40));

        btnok.setBackground(new java.awt.Color(0, 153, 153));
        btnok.setForeground(new java.awt.Color(255, 255, 255));
        btnok.setText("OK");
        btnok.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnokMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnokMousePressed(evt);
            }
        });
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });
        jPanel1.add(btnok, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 60, 35));

        txtsquestion.setFont(new java.awt.Font("Futura Bk BT", 0, 16)); // NOI18N
        txtsquestion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtsquestion.setEnabled(false);
        txtsquestion.setMinimumSize(new java.awt.Dimension(100, 40));
        txtsquestion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsquestionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsquestionFocusLost(evt);
            }
        });
        txtsquestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsquestionActionPerformed(evt);
            }
        });
        jPanel1.add(txtsquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 420, -1));

        lblpass1.setFont(new java.awt.Font("Futura Md BT", 0, 20)); // NOI18N
        lblpass1.setForeground(new java.awt.Color(255, 255, 255));
        lblpass1.setText("New Password");
        jPanel1.add(lblpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 30));

        txtanswer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtanswer.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtanswer.setMinimumSize(new java.awt.Dimension(100, 40));
        txtanswer.setPreferredSize(new java.awt.Dimension(109, 31));
        txtanswer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtanswerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtanswerFocusLost(evt);
            }
        });
        jPanel1.add(txtanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 212, 420, -1));

        lblpass2.setFont(new java.awt.Font("Futura Md BT", 0, 20)); // NOI18N
        lblpass2.setForeground(new java.awt.Color(255, 255, 255));
        lblpass2.setText(" Answer");
        jPanel1.add(lblpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 30));

        lblpass3.setFont(new java.awt.Font("Futura Md BT", 0, 20)); // NOI18N
        lblpass3.setForeground(new java.awt.Color(255, 255, 255));
        lblpass3.setText("Question");
        jPanel1.add(lblpass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusGained
        // TODO add your handling code here:
        if(txtid.getText().equals("Username")) {
            txtid.setText("");
        }
        else {
            txtid.selectAll();
        }
    }//GEN-LAST:event_txtidFocusGained

    private void txtidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusLost
        // TODO add your handling code here:
        if(txtid.getText().equals("")) {
            txtid.setText("Username");
        }
    }//GEN-LAST:event_txtidFocusLost

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnewpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnewpasswordFocusGained
        // TODO add your handling code here:
        if(txtnewpassword.getText().equals("Password")) {
            txtnewpassword.setText("");
        }
        else {
            txtnewpassword.selectAll();
        }
    }//GEN-LAST:event_txtnewpasswordFocusGained

    private void txtnewpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnewpasswordFocusLost
        // TODO add your handling code here:
        if(txtnewpassword.getText().equals("")) {
            txtnewpassword.setText("Password");
        }
    }//GEN-LAST:event_txtnewpasswordFocusLost

    private void btnconfirmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmMousePressed
       
    }//GEN-LAST:event_btnconfirmMousePressed

    private void btnconfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnconfirmMouseExited

    private void btnconfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnconfirmMouseEntered

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
        String username = txtid.getText();
        String newpassword = txtnewpassword.getText();
        String squestion=txtsquestion.getText();
        String answer=txtanswer.getText();

        try {
            Connection con = DriverManager.getConnection(surl,suser,spassword);
            //Connection connection = ConnectDatabase.getConnection();
            PreparedStatement st = (PreparedStatement) con.prepareStatement("Select * from signup3 where email='"+username+"' and Hints='"+answer+"'");
            ResultSet rs = st.executeQuery();
            if (rs.next()) {
                //st.executeUpdate("update users set password= '"+newpassword+"' where userid='"+username+"' and student.sanswer='"+answer+"'");
                st.executeUpdate("update login u INNER JOIN signup3 s ON u.uid=s.email set u.pwd= '"+newpassword+"' where u.uid='"+username+"' and s.Hints='"+answer+"'");
                JOptionPane.showMessageDialog(null,"Your password sucessfully updated");
               Login lg=new Login();
                lg.setVisible(true);
                dispose();

            } else {
                JOptionPane.showMessageDialog(null,  "Wrong information Passed by You","Uh-oh!",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException sqlException) {
        }
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void btnsigninMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsigninMousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnsigninMousePressed

    private void btnsigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsigninMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnsigninMouseExited

    private void btnsigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsigninMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnsigninMouseEntered

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
        // TODO add your handling code here:

        Login login=new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnsigninActionPerformed

    private void btnokMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnokMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnokMousePressed

    private void btnokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnokMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnokMouseExited

    private void btnokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnokMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnokMouseEntered

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        String userid = txtid.getText();
        String password = txtnewpassword.getText();
        if(txtid.getText().equals("Username")){
            JOptionPane.showMessageDialog(null, "Text Box cannot left blank");
        }
        else
        {
            try {
                Connection con = DriverManager.getConnection(surl,suser,spassword);
                //Connection connection = DriverManager.getConnection(surl,suser,spassword);
                PreparedStatement st =con.prepareStatement("Select question from signup3 where email='"+userid +"'");

                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    txtsquestion.setText(rs.getString(1));
                    new forgot2().setSize(562, 450);
                    lblpass3.setVisible(true);
                    lblpass1.setVisible(true);
                    lblpass2.setVisible(true);
                    txtsquestion.setVisible(true);
                    txtanswer.setVisible(true);
                    txtnewpassword.setVisible(true);
                    btnsignin.setVisible(true);
                    btnconfirm.setVisible(true);
                }
                else {
                    lblpass3.setVisible(false);
                    lblpass1.setVisible(false);
                    lblpass2.setVisible(false);
                    txtsquestion.setVisible(false);
                    txtanswer.setVisible(false);
                    txtnewpassword.setVisible(false);
                    btnsignin.setVisible(false);
                    btnconfirm.setVisible(false);
                    txtsquestion.setText("");
                    JOptionPane.showMessageDialog(null,  "Wrong Username ","Uh-oh!", JOptionPane.ERROR_MESSAGE);

                }
            } catch (SQLException sqlException) {
            }
        }
    }//GEN-LAST:event_btnokActionPerformed

    private void txtsquestionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsquestionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsquestionFocusGained

    private void txtsquestionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsquestionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsquestionFocusLost

    private void txtsquestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsquestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsquestionActionPerformed

    private void txtanswerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtanswerFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanswerFocusGained

    private void txtanswerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtanswerFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanswerFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconfirm;
    private javax.swing.JButton btnok;
    private javax.swing.JButton btnsignin;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblheader;
    private javax.swing.JLabel lblpass1;
    private javax.swing.JLabel lblpass2;
    private javax.swing.JLabel lblpass3;
    private javax.swing.JLabel lbluser;
    private javax.swing.JPasswordField txtanswer;
    private javax.swing.JTextField txtid;
    private javax.swing.JPasswordField txtnewpassword;
    private javax.swing.JTextField txtsquestion;
    // End of variables declaration//GEN-END:variables
}
